# Values used for the deployed application.
replicaCount: 1
service:
  name: content-rw-s3
bucket:
  key: "generic-rw-s3.bucket"
env:
  bucket:
    name: "com.ft.universalpublishing.enrichedcontentdata"
    prefix: "unarchived"
  log:
    metrics: "false"
