# Values used for the deployed application.
service:
  name: upp-exports-rw-s3
env:
  BUCKET_NAME: "com.ft.universalpublishing.enrichedcontentdata.test"
  BUCKET_CONTENT_PREFIX: "k8s-staging-content-unarchived"
  BUCKET_CONCEPT_PREFIX: "k8s-staging-concept-unarchived"
  CONTENT_RESOURCE_PATH: "content"
  CONCEPT_RESOURCE_PATH: "concept"
  LOG_METRICS: "false"
